import { z } from 'zod';
import { prepQuestionKinds } from '../types/prep.ts';
import { classificationSchema } from './classification.ts';

export const prepQuestionKindSchema = z.enum(prepQuestionKinds);

/**
 * The list-questions input toggles between unanswered (default — the
 * actual queue) and all (audit / triage view).
 */
export const listPrepQuestionsInputSchema = z.object({
  includeAnswered: z.boolean().optional(),
});
export type ListPrepQuestionsInput = z.infer<typeof listPrepQuestionsInputSchema>;

export const getPrepQuestionInputSchema = z.object({
  key: z.string().min(1),
});
export type GetPrepQuestionInput = z.infer<typeof getPrepQuestionInputSchema>;

export const listForPathInputSchema = z.object({
  pathId: z.string().min(1),
});
export type ListForPathInput = z.infer<typeof listForPathInputSchema>;

/**
 * Answer payload is kind-discriminated. Today only `classification` is
 * generated by the analyzer; the other kinds reserve shape so the
 * prep router and client UI don't need a refactor when later chunks
 * start emitting them.
 */
export const prepAnswerPayloadSchema = z.discriminatedUnion('kind', [
  z.object({ kind: z.literal('classification'), classification: classificationSchema }),
  z.object({ kind: z.literal('path_branch'), chosenIdentity: z.string().min(1) }),
  z.object({ kind: z.literal('entry_point'), entryPointId: z.string().min(1) }),
  z.object({ kind: z.literal('intent'), text: z.string().min(1).max(4000) }),
  z.object({
    kind: z.literal('rename'),
    decision: z.enum(['carry_forward', 'treat_as_new']),
  }),
]);

export const answerPrepQuestionInputSchema = z.object({
  key: z.string().min(1),
  answer: prepAnswerPayloadSchema,
});
export type AnswerPrepQuestionInput = z.infer<typeof answerPrepQuestionInputSchema>;
