/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PrepRouteImport } from './routes/prep'
import { Route as CodebaseRouteImport } from './routes/codebase'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevStylesRouteImport } from './routes/dev/styles'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project/$projectId/index'
import { Route as ProjectProjectIdFilesIndexRouteImport } from './routes/project/$projectId/files/index'
import { Route as ProjectProjectIdPathPathIdRouteImport } from './routes/project/$projectId/path.$pathId'
import { Route as ProjectProjectIdFilesSplatRouteImport } from './routes/project/$projectId/files/$'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepRoute = PrepRouteImport.update({
  id: '/prep',
  path: '/prep',
  getParentRoute: () => rootRouteImport,
} as any)
const CodebaseRoute = CodebaseRouteImport.update({
  id: '/codebase',
  path: '/codebase',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevStylesRoute = DevStylesRouteImport.update({
  id: '/dev/styles',
  path: '/dev/styles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/project/$projectId/',
  path: '/project/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdFilesIndexRoute =
  ProjectProjectIdFilesIndexRouteImport.update({
    id: '/project/$projectId/files/',
    path: '/project/$projectId/files/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectProjectIdPathPathIdRoute =
  ProjectProjectIdPathPathIdRouteImport.update({
    id: '/project/$projectId/path/$pathId',
    path: '/project/$projectId/path/$pathId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectProjectIdFilesSplatRoute =
  ProjectProjectIdFilesSplatRouteImport.update({
    id: '/project/$projectId/files/$',
    path: '/project/$projectId/files/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/codebase': typeof CodebaseRoute
  '/prep': typeof PrepRoute
  '/progress': typeof ProgressRoute
  '/rules': typeof RulesRoute
  '/dev/styles': typeof DevStylesRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/files/$': typeof ProjectProjectIdFilesSplatRoute
  '/project/$projectId/path/$pathId': typeof ProjectProjectIdPathPathIdRoute
  '/project/$projectId/files/': typeof ProjectProjectIdFilesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/codebase': typeof CodebaseRoute
  '/prep': typeof PrepRoute
  '/progress': typeof ProgressRoute
  '/rules': typeof RulesRoute
  '/dev/styles': typeof DevStylesRoute
  '/project/$projectId': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/files/$': typeof ProjectProjectIdFilesSplatRoute
  '/project/$projectId/path/$pathId': typeof ProjectProjectIdPathPathIdRoute
  '/project/$projectId/files': typeof ProjectProjectIdFilesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/codebase': typeof CodebaseRoute
  '/prep': typeof PrepRoute
  '/progress': typeof ProgressRoute
  '/rules': typeof RulesRoute
  '/dev/styles': typeof DevStylesRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/files/$': typeof ProjectProjectIdFilesSplatRoute
  '/project/$projectId/path/$pathId': typeof ProjectProjectIdPathPathIdRoute
  '/project/$projectId/files/': typeof ProjectProjectIdFilesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/codebase'
    | '/prep'
    | '/progress'
    | '/rules'
    | '/dev/styles'
    | '/project/$projectId/'
    | '/project/$projectId/files/$'
    | '/project/$projectId/path/$pathId'
    | '/project/$projectId/files/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/codebase'
    | '/prep'
    | '/progress'
    | '/rules'
    | '/dev/styles'
    | '/project/$projectId'
    | '/project/$projectId/files/$'
    | '/project/$projectId/path/$pathId'
    | '/project/$projectId/files'
  id:
    | '__root__'
    | '/'
    | '/codebase'
    | '/prep'
    | '/progress'
    | '/rules'
    | '/dev/styles'
    | '/project/$projectId/'
    | '/project/$projectId/files/$'
    | '/project/$projectId/path/$pathId'
    | '/project/$projectId/files/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodebaseRoute: typeof CodebaseRoute
  PrepRoute: typeof PrepRoute
  ProgressRoute: typeof ProgressRoute
  RulesRoute: typeof RulesRoute
  DevStylesRoute: typeof DevStylesRoute
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
  ProjectProjectIdFilesSplatRoute: typeof ProjectProjectIdFilesSplatRoute
  ProjectProjectIdPathPathIdRoute: typeof ProjectProjectIdPathPathIdRoute
  ProjectProjectIdFilesIndexRoute: typeof ProjectProjectIdFilesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prep': {
      id: '/prep'
      path: '/prep'
      fullPath: '/prep'
      preLoaderRoute: typeof PrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codebase': {
      id: '/codebase'
      path: '/codebase'
      fullPath: '/codebase'
      preLoaderRoute: typeof CodebaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/styles': {
      id: '/dev/styles'
      path: '/dev/styles'
      fullPath: '/dev/styles'
      preLoaderRoute: typeof DevStylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/project/$projectId'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/files/': {
      id: '/project/$projectId/files/'
      path: '/project/$projectId/files'
      fullPath: '/project/$projectId/files/'
      preLoaderRoute: typeof ProjectProjectIdFilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/path/$pathId': {
      id: '/project/$projectId/path/$pathId'
      path: '/project/$projectId/path/$pathId'
      fullPath: '/project/$projectId/path/$pathId'
      preLoaderRoute: typeof ProjectProjectIdPathPathIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/files/$': {
      id: '/project/$projectId/files/$'
      path: '/project/$projectId/files/$'
      fullPath: '/project/$projectId/files/$'
      preLoaderRoute: typeof ProjectProjectIdFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodebaseRoute: CodebaseRoute,
  PrepRoute: PrepRoute,
  ProgressRoute: ProgressRoute,
  RulesRoute: RulesRoute,
  DevStylesRoute: DevStylesRoute,
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
  ProjectProjectIdFilesSplatRoute: ProjectProjectIdFilesSplatRoute,
  ProjectProjectIdPathPathIdRoute: ProjectProjectIdPathPathIdRoute,
  ProjectProjectIdFilesIndexRoute: ProjectProjectIdFilesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
