/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CodebaseRouteImport } from './routes/codebase'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevStylesRouteImport } from './routes/dev/styles'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project/$projectId/index'
import { Route as ProjectProjectIdPathPathIdRouteImport } from './routes/project/$projectId/path.$pathId'

const CodebaseRoute = CodebaseRouteImport.update({
  id: '/codebase',
  path: '/codebase',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevStylesRoute = DevStylesRouteImport.update({
  id: '/dev/styles',
  path: '/dev/styles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/project/$projectId/',
  path: '/project/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdPathPathIdRoute =
  ProjectProjectIdPathPathIdRouteImport.update({
    id: '/project/$projectId/path/$pathId',
    path: '/project/$projectId/path/$pathId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/codebase': typeof CodebaseRoute
  '/dev/styles': typeof DevStylesRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/path/$pathId': typeof ProjectProjectIdPathPathIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/codebase': typeof CodebaseRoute
  '/dev/styles': typeof DevStylesRoute
  '/project/$projectId': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/path/$pathId': typeof ProjectProjectIdPathPathIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/codebase': typeof CodebaseRoute
  '/dev/styles': typeof DevStylesRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/path/$pathId': typeof ProjectProjectIdPathPathIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/codebase'
    | '/dev/styles'
    | '/project/$projectId/'
    | '/project/$projectId/path/$pathId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/codebase'
    | '/dev/styles'
    | '/project/$projectId'
    | '/project/$projectId/path/$pathId'
  id:
    | '__root__'
    | '/'
    | '/codebase'
    | '/dev/styles'
    | '/project/$projectId/'
    | '/project/$projectId/path/$pathId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodebaseRoute: typeof CodebaseRoute
  DevStylesRoute: typeof DevStylesRoute
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
  ProjectProjectIdPathPathIdRoute: typeof ProjectProjectIdPathPathIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/codebase': {
      id: '/codebase'
      path: '/codebase'
      fullPath: '/codebase'
      preLoaderRoute: typeof CodebaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/styles': {
      id: '/dev/styles'
      path: '/dev/styles'
      fullPath: '/dev/styles'
      preLoaderRoute: typeof DevStylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/project/$projectId'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/path/$pathId': {
      id: '/project/$projectId/path/$pathId'
      path: '/project/$projectId/path/$pathId'
      fullPath: '/project/$projectId/path/$pathId'
      preLoaderRoute: typeof ProjectProjectIdPathPathIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodebaseRoute: CodebaseRoute,
  DevStylesRoute: DevStylesRoute,
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
  ProjectProjectIdPathPathIdRoute: ProjectProjectIdPathPathIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
