/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CodebaseRouteImport } from './routes/codebase'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevStylesRouteImport } from './routes/dev/styles'

const CodebaseRoute = CodebaseRouteImport.update({
  id: '/codebase',
  path: '/codebase',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevStylesRoute = DevStylesRouteImport.update({
  id: '/dev/styles',
  path: '/dev/styles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/codebase': typeof CodebaseRoute
  '/dev/styles': typeof DevStylesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/codebase': typeof CodebaseRoute
  '/dev/styles': typeof DevStylesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/codebase': typeof CodebaseRoute
  '/dev/styles': typeof DevStylesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/codebase' | '/dev/styles'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/codebase' | '/dev/styles'
  id: '__root__' | '/' | '/codebase' | '/dev/styles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodebaseRoute: typeof CodebaseRoute
  DevStylesRoute: typeof DevStylesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/codebase': {
      id: '/codebase'
      path: '/codebase'
      fullPath: '/codebase'
      preLoaderRoute: typeof CodebaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/styles': {
      id: '/dev/styles'
      path: '/dev/styles'
      fullPath: '/dev/styles'
      preLoaderRoute: typeof DevStylesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodebaseRoute: CodebaseRoute,
  DevStylesRoute: DevStylesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
